// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Data;

#nullable disable

namespace RecipeShare.Data.Migrations
{
    [DbContext(typeof(RecipeShareDbContext))]
    [Migration("20260402120713_UpdateContentField")]
    partial class UpdateContentField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 2, 13, 7, 12, 891, DateTimeKind.Local).AddTicks(2336),
                            RecipeId = 1,
                            Text = "Harika bir tarif, denedim çok güzel oldu!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 2, 14, 7, 12, 891, DateTimeKind.Local).AddTicks(2341),
                            RecipeId = 1,
                            Text = "Tuzu biraz az geldi ama kıvamı müthiş.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 2, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2342),
                            RecipeId = 2,
                            Text = "Çok lezzetli görünüyor, elinize sağlık.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 2, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2343),
                            RecipeId = 2,
                            Text = "Blenderdan geçirmeden önce süzmek daha iyi sonuç veriyor.",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Tereyağını sahanda eritip köpürmesini bekleyin. Yumurtaları sarılarını bozmadan kırın, üzerine bir tutam tuz ve pul biber ekleyerek beyazları tamamen pişene kadar orta ateşte tutun.",
                            CreatedDate = new DateTime(2026, 3, 28, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2303),
                            ImageUrl = "/images/default-recipe.jpg",
                            Title = "Sahanda Yumurta",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Soğan, havuç ve patatesi kavurduktan sonra yıkanmış kırmızı mercimeği ekleyin. Sıcak su ilavesiyle mercimekler yumuşayana kadar haşlayıp blenderdan geçirin. Üzerine kızgın tereyağlı sos dökün.",
                            CreatedDate = new DateTime(2026, 3, 29, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2325),
                            ImageUrl = "/images/default-recipe.jpg",
                            Title = "Mercimek Çorbası",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "İnce açılmış hamurun üzerine taze fesleğenli domates sosu ve bol mozarella peyniri yayın. Tercihen taş fırında veya 250 derece ısıtılmış fırında kenarları çıtırlaşana kadar yaklaşık 10 dakika pişirin.",
                            CreatedDate = new DateTime(2026, 3, 30, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2327),
                            ImageUrl = "/images/default-recipe.jpg",
                            Title = "İtalyan Usulü Pizza",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Dinlendirilmiş dana kıymadan hazırlanan kalın köfteleri döküm tavada mühürleyin. Karamelize soğan, cheddar peyniri ve özel burger sosu ile ısıtılmış brioche ekmeği arasında servis yapın.",
                            CreatedDate = new DateTime(2026, 3, 31, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2328),
                            ImageUrl = "/images/default-recipe.jpg",
                            Title = "Ev Yapımı Burger",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Garnitür karışımını (bezelye, havuç, patates) limonlu suda bekletilmiş enginarların ortasına yerleştirin. Bol sızma zeytinyağı, bir tutam şeker ve portakal suyu ekleyerek kısık ateşte yumuşayana kadar pişirin.",
                            CreatedDate = new DateTime(2026, 4, 1, 15, 7, 12, 891, DateTimeKind.Local).AddTicks(2329),
                            ImageUrl = "/images/default-recipe.jpg",
                            Title = "Zeytinyağlı Enginar",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bariscoskun441@gmail.com",
                            PasswordHash = "1234",
                            RoleId = 1,
                            Username = "bariscoskun"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ali@mail.com",
                            PasswordHash = "abcd5678",
                            RoleId = 2,
                            Username = "yazilimci_ali"
                        },
                        new
                        {
                            Id = 3,
                            Email = "doga@mail.com",
                            PasswordHash = "efgh5678",
                            RoleId = 1,
                            Username = "doga_chef"
                        },
                        new
                        {
                            Id = 4,
                            Email = "robot@mail.com",
                            PasswordHash = "1234",
                            RoleId = 2,
                            Username = "mutfak_robotu"
                        });
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Comment", b =>
                {
                    b.HasOne("RecipeShare.Data.Entities.Recipe", "Recipe")
                        .WithMany("Comment")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeShare.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Recipe", b =>
                {
                    b.HasOne("RecipeShare.Data.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.User", b =>
                {
                    b.HasOne("RecipeShare.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RecipeShare.Data.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
